trigger:
- main  # Change this to your branch name

pool:
  name: 'Azdemo'  # Change this to your agent pool name
  # demands:
  #   - agent.name -equals <your_agent_name>  # Replace <your_agent_name> with your self-hosted agent name

jobs:
- job: RunPythonScript
  displayName: 'Run Python Script Job'
  pool:
    name: 'Azdemo'  # Change this to your agent pool name
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.12'

  - script: |
      python -m pip install --upgrade pip
    displayName: 'Install Dependencies'

  - task: CmdLine@2
    inputs:
      script: |
        echo Write your commands here
        echo Hello world
