trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  # - script: |
  #     az login --service-principal --username <client-id> --password <client-secret> --tenant <tenant-id>
  #     az account set --subscription <subscription-id>
  #     az group create --name <resource-group> --location <location>
  #     az deployment group create --resource-group <resource-group> --template-file azuredeploy.json --parameters azuredeploy.parameters.json
  #   displayName: 'Deploy to Azure'

  # - task: AzureWebApp@1
  #   inputs:
  #     azureSubscription: '<azure-subscription>'
  #     appName: '<app-name>'
  #     package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
  #   displayName: 'Deploy to Azure Web App'